name: Schedule Download and Sync from Google Drive

on:
  schedule:
    # 12 hourly
    - cron: '0 */12 * * *'

permissions: 
  contents: write

jobs:
    download_and_sync:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Print Directory Contents
              run: ls -al

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install gdown

            - name: Download files from Google Drive
              env: 
                OUTPUT_DIR: "./content"
              run: |
                  gdown --folder --id "${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}" --output "${{ env.OUTPUT_DIR }}"
                  ls -al ${{ env.OUTPUT_DIR }}

            - name: Check diff
              run: |
                    datetime=$(date +'%Y-%m-%d')
                    diff=$(git diff --name-only)
                    if [ -n "$diff" ]; then
                        echo "Files have changed. Committing changes..."
                        git config user.email "${{ github.actor }}@users.noreply.github.com"
                        git config user.name "${{ github.actor }}"
                        git add .
                        git commit -m "Google Drive Sync $datetime"
                        git push origin ${{ github.head_ref || github.ref }}
                    else
                        echo "No changes detected."
                    fi

            - name: Push Commit
              run: |
                    git push origin ${{ github.head_ref || github.ref }}